# sosohu configuration

name: WordWorth
description: sosohu

# url is currently only used only for the RSS feed in feed.xml
url: http://sosohu.github.io/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: 

# This can be '' to hide the Github nav button
github: 'sosohu/sosohu.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'sosohu'
comments: true

permalink: /:year/:month/:title
paginate: 3
safe: false

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
